### ISSUE TITLE
Items disappear upon click, crafting interface doesn't work (tModloader 1.4)

### ISSUE THREAD

**Issue by liraeli** [blushiemagic/MagicStorage#139] opened 2021-11-01 08:33 UTC
tModLoader version v0.12 1.4 Alpha ffb60956, built 31/10/2021 7:25AM
Magic Storage version v0.5.1.2.

Any item stack disappears after left clicking it, right clicking causes one item in a stack to disappear.  Depositing items is still possible, but they run into the same issue for retrieval.
The issue seems to occur exclusively in multiplayer, but regardless of whether additional players are online, and will also occur without any other mods installed, on a new world.
The issue appears to persist with new storage units, using the storage wand to turn the units off, removing the units and replacing them, using a storage access and using a remote access.

A secondary issue is that the storage crafting interface doesn't work at all, singleplayer/multiplayer. The crafting stations within the interface aren't able to be grabbed, and don't appear as items when you hover over them. The crafting recipes are clickable, and still appear, but they cannot be crafted.

**Comment by Tepig125** [comment] 2021-11-23 05:33
I can confirm that the crafting interface doesn't work in the 1.4 alpha (as of 11/22/2021), and in fact, simply hovering over any slot for a crafting station within the crafting interface prints an error message into the chat, even if the only mods active are Magic Storage (and Hero's Mod for easier testing)

The message is normally very hard to see due to being written entirely in black, so I enabled light hack via Hero's Mod and took a screenshot of the message:
![image](https://user-images.githubusercontent.com/69269327/142975201-2dd8b1fc-54d5-4947-a34d-70ecce19a14f.png)

Since it's still pretty hard to read, here is the first line in the message:
`System.MissingMethodException: Method not found: Void Terraria.Player.QuickSpawnClonedItem(Terraria.Item, Int32)`
The rest is just a stack trace starting at `MagicStorage.CraftingGUI.HoverStation`, which is presumably what caused the error

**Comment by cooooody** [comment] 2021-11-30 07:44
I also have been having the same problem, if you mosue over any of the slots in the crafting inteface or try to cheese it by holding ctrl and clicking it will pop up. also there are about 20 slots for crafting benches. https://puu.sh/IsxrI/4d0d2fd6aa.png

**Comment by ExterminatorX99** [comment] 2021-11-30 13:39
This is a known issue that the dev will fix when he finishes some real life stuff.
In the mean time, there is a temporary fix on the [Magic Strage discord](https://discord.gg/FemPG7eev4)

**Comment by absoluteAquarian** [comment] 2021-12-16 15:14
Issue was fixed by Yowave's temporary builds and the recent update in the Workshop

**Closed by absoluteAquarian** 2021-12-16 15:14 UTC
