### ISSUE TITLE
Incompatible with Kalciphoz's RPG Mod  

### ISSUE THREAD

**Issue by charlestain** [blushiemagic/MagicStorage#35] opened 2017-12-01 12:07 UTC
sorry to bother you but i have noticed that your mod doesnt work with the rpg mod as when you try to open the storage the menu doesnt show up so i was wondering if by any chance there is a simple fix that i could do or is it more complicated ? thank you.

**Comment by whismerhill** [comment] 2018-02-24 02:38
#33

**Comment by blushiemagic** [comment] 2018-08-22 05:00
Duplicate of #33

**Closed by blushiemagic** 2018-08-22 05:00 UTC
